### ISSUE TITLE
libguestfs-tools for urbackup

### ISSUE THREAD

**Issue by masterwishx** [ich777/slackware#2]
can you add libguestfs-tools for urbackup?
if it can work in Unraid at all ?!?

i added template xml of urBackup official, this needs to image mounting .
https://libguestfs.org/

**Comment by ich777** [comment]
I will look into that, please give me a few days.

**Comment by ich777** [comment]
@masterwishx I've now took a quick look into it but the dependencies are a nightmare.
What do you want to do with it exactly?

**Comment by masterwishx** [comment]
> What do you want to do with it exactly?

It's for mount images in urbackup. 

I just switched from binhex-urbackup to official urbackup container that I made xml template for it. 
But found then that binhex implemented libguestfs-tools in his container, so I think will be  better that author of container will add it instead of adding package to unraid.

**Comment by ich777** [comment]
> But found then that binhex implemented libguestfs-tools in his container, so I think will be better that author of container will add it instead of adding package to unraid.

Yes, but I'm not too sure if that will work very well.
As said it would be possible but it is very complicated because a few dependencies need to be compiled too.

Is this now solved and you add it to the container or use binhex-urbackup? If yes, please close the issue.

**Comment by masterwishx** [comment]
I used binhex-urbackup, now using uroni/urbackup and hope he will add it....
