### ISSUE TITLE
Add a package for pixz

### ISSUE THREAD

**Issue by ELind77** [ich777/slackware#3]
Hi ich777,

I love having `un-get` as a package installer for unRAID, I feel like the ecosystem was really missing a CLI package installer, so thank you for all of your work.  

I would love to have the [pixz](https://github.com/vasi/pixz) compression tool added to this repository.  It's a wonderful extension to the standard xz (LZMA) compression tool that allows random access to files in the archive.  For large tarballs, the ability to extract any arbitrary file, and show the archive index without reading the rest of the files in the archive (constant time access) is an amazing benefit.   

I deal with 4-10 GB archives in my day to day work and I find that I have a lot of compressed tarballs around in unRAID as well, both large and small.  Take CA USB backups for example, that plugin is practically a built-in at this point and the backups are all tarballs.  My `appdata` tar.gz backups are around 8 GB, which I think is on the smaller side and even thought CA backups now supports a separate tarball for each subdirectory, The ability to pick just one file or folder to extract from a backup would be amazing.  I'm not saying this would get rolled into CA backups, but I think it's a nice example that most people in our community.  

I'm not sure how much work it would take to get pixz packaged for slackware (unRAID doesn't have the dependencies to build from source and I havent' been able to get it to compile statically).  But I would very much appreciate it if you would at least look into it.

Best,

Eric

**Comment by ich777** [comment]
Hi, thanks for the request.
I will look into it but you have to give me a bit since I‘m really busy in real life bit I‘ll try my best amd will report back.

**Comment by ich777** [comment]
@ELind77 please run:
```
un-get update
un-get install pixz
```

Please report back if it is working as expected.

**Comment by ELind77** [comment]
It's perfect! Thank you!
